routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//  login route
Route::get('/', function () {
    return view('admin.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//  Admin auth
Route::match(['get', 'post'], '/Admin/Auth', 'AdminController@authentication');

Route::group(['middleware' => ['auth']], function () {

    //  middelware Authentication
    Route::match(['get', 'post'], '/company/dashboard', [CompanyController::class, 'dashboard']);

    Route::resource('companies', 'CompanyController');

    Route::resource('employees', 'EmployeeController');
});
//  Logout Middelware
Route::get('/logout', 'AdminController@logout');

resources/views/admin/addemployee/create.blade.php
@extends('admin.layouts.master')
@section('title','Add Employees')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
       <div class="header-icon">
          <i class="fa fa-users"></i>
       </div>
       <div class="header-title">
          <h1>Add Employees</h1>
          <small>Add Employees</small>
       </div>
    </section>
    @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        
    <!-- Main content -->
    <section class="content">
     
       <div class="row">
          <!-- Form controls -->
          <div class="col-sm-12">
             <div class="panel panel-bd lobidrag">
                <div class="panel-heading">
                   <div class="btn-group" id="buttonlist"> 
                   <a class="btn btn-add " href="{{route('employees.index')}}"> 
                      <i class="fa fa-eye"></i>  View Employess </a>  
                   </div>
                </div>
                <div class="panel-body">
                  <form action="{{ route('employees.store') }}" method="post">
                     @csrf
                     <div class="form-group">
                       <label for="">First Name :</label>
                     <input type="text" name="first_name" id="" class="form-control" placeholder="Enter your First name" value="{{old('first_name')}}" >
                     </div>
                     <div class="form-group">
                        <label for="">Last Name :</label>
                      <input type="text" name="last_name" id="" class="form-control" placeholder="Enter your Last name" value="{{old('last_name')}}" >
                      </div>
                     <div class="form-group">
                       <label for="">Email :</label>
                       <input type="text" name="email" id="" class="form-control" placeholder="Enter your email" value="{{old('email')}}" >
                     </div>
                     <div class="form-group">
                        <label for="">Select Company :</label>
                        <select name="companyid" class="form-control" id="">
                            @foreach ($comp as $companies)
                                <option value="{{$companies['id']}}">{{$companies['name']}}</option>
                            @endforeach
                        </select>
                        <div class="form-group">
                            <label for="">Phone Number # :</label>
                            <input type="text" name="phone_number" autocomplete="off" id="" class="form-control" placeholder="Enter your phone" value="{{old('phone_number')}}" >
                          </div>
                      
                    
                    
         
                     <br>
                     <input type="submit" value="Submit Form" class="btn btn-info btn-lg">
         
                 </form>
                </div>
             </div>
          </div>
       </div>
    </section>
    <!-- /.content -->
 </div>
@endsection

resources/views/admin/addemployee/edit.blade.php
@extends('admin.layouts.master')
@section('title','Edit Product')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
       <div class="header-icon">
          <i class="fa fa-users"></i>
       </div>
       <div class="header-title">
          <h1>Edit Company</h1>
          <small>Edit Company</small>
       </div>
    </section>
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
@endif
        
    <!-- Main content -->
    <section class="content">
       <div class="row">
          <!-- Form controls -->
          <div class="col-sm-12">
             <div class="panel panel-bd lobidrag">
                <div class="panel-heading">
                   <div class="btn-group" id="buttonlist"> 
                      <a class="btn btn-add " href="{{url('admin/view-product')}}"> 
                      <i class="fa fa-eye"></i>  View Companies </a>  
                   </div>
                </div>
                <div class="panel-body">
                    <form action="{{ route('employees.update',$employee->id) }}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="">First Name :</label>
                          <input type="text" name="first_name" id="" class="form-control" placeholder="Enter your First name" value="{{$employee->firstname}}" >
                          </div>
                          <div class="form-group">
                             <label for="">Last Name :</label>
                           <input type="text" name="last_name" id="" class="form-control" placeholder="Enter your Last name" value="{{$employee->lastname}}" >
                           </div>
                          <div class="form-group">
                            <label for="">Email :</label>
                            <input type="text" name="email" id="" class="form-control" placeholder="Enter your email" value="{{$employee->email}}" >
                          </div>
                          <div class="form-group">
                             <label for="">Select Company :</label>
                             <select name="companyid" class="form-control" id="">
                                 @foreach ($comp as $companies)
                                     <option value="{{$companies['id']}}">{{$companies['name']}}</option>
                                 @endforeach
                             </select>
                          </div>
                             <div class="form-group">
                                 <label for="">Phone Number # :</label>
                                 <input type="text" name="phone_number" autocomplete="off" id="" class="form-control" placeholder="Enter your phone" value="{{$employee->phone}}" >
                               </div>
                           
          
                        <br>
                        <input type="submit" value="Submit Form" class="btn btn-info btn-lg">
                
                    </form>
                </div>
             </div>
          </div>
       </div>
    </section>
    <!-- /.content -->
 </div>
@endsection

resources/views/admin/addemployee/index.blade.php
@extends('admin.layouts.master')
@section('title','View Company')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
       <div class="header-icon">
          <i class="fa fa-product-hunt"></i>
       </div>
       <div class="header-title">
          <h1>View Employee</h1>
          <small>Employee List</small>
       </div>
    </section>
    <!-- Main content -->
    <section class="content">
       <div class="row">
          <div class="col-sm-12">
             <div class="panel panel-bd lobidrag">
                <div class="panel-heading">
                   <div class="btn-group" id="buttonexport">
                      <a href="#">
                         <h4>View Employee</h4>
                      </a>
                   </div>
                </div>
                <div class="panel-body">
                <!-- Plugin content:powerpoint,txt,pdf,png,word,xl -->
                @if (session()->has('success'))
                <div class="alert alert-success">
                    {{session()->get('success')}}
                </div>
            @endif
            @if (session()->has('error'))
                <div class="alert alert-danger">
                    {{session()->get('error')}}
                </div>
            @endif

                   <div class="btn-group">
                      <div class="buttonexport" id="buttonlist"> 
                         <a class="btn btn-add" href="{{ route('employees.create') }}"> <i class="fa fa-plus"></i> Add Employee
                         </a>  
                      </div>
                   </div>
                   <!-- Plugin content:powerpoint,txt,pdf,png,word,xl -->
                   <div class="table-responsive">
                      <table id="table_id" class="table table-bordered table-striped table-hover">
                         <thead>
                            <tr class="info">
                                
                               <th>Fist Name</th>
                               <th>Last NAme</th>
                               <th>Email</th>
                               <th>Company Name</th>
                               <th>Phone</th>
                               <th>Show</th>
                               <th>Edit</th>
                               <th>Delete</th>

                            </tr>
                         </thead>
                         <tbody>

                             @foreach ($comp as $item)
                             <tr>
                                <td>{{$item->firstname}}</td>
                                <td>{{$item->lastname}}</td>
                                <td>{{$item->email}}</td>
                                <td>{{$item->company->name}}</td>
                                <td>{{$item->phone}}</td>

                                <td>
                                 <a href="{{ route('employees.show',$item->id) }}" class="btn btn-primary">Show</a>
                             </td>

                                <td>
                                    <a href="{{ route('employees.edit',$item->id) }}" class="btn btn-success">Edit</a>
                                </td>
                                 <td>
                                    <form action="{{ route('employees.destroy',$item->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <input type="submit" value="Delete" class="btn btn-danger">
                                    </form>
                                </td>
                                
                               
                             </tr>
                             @endforeach
                          
                            
                         </tbody>
                      </table>
                      <div class="d-flex justify-content-center align-items-center">
                        <div>{{$comp->links()}}</div>
                    </div>
                   </div>
                </div>
             </div>
          </div>
       </div>
       <!-- customer Modal1 -->
     
       <!-- /.modal -->
    </section>
    <!-- /.content -->
 </div> 
@endsection

resources/views/admin/addemployee/show.blade.php
@extends('admin.layouts.master')
@section('title',' Employee Details')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
       <div class="header-icon">
          <i class="fa fa-users"></i>
       </div>
       <div class="header-title">
          <h1>Employee Detials</h1>
          <small>Employee Detials</small>
       </div>
    </section>
    @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        
    <!-- Main content -->
    <section class="content">
     
       <div class="row">
          <!-- Form controls -->
          <div class="col-sm-12">
             <div class="panel panel-bd lobidrag">
                <div class="panel-heading">
                   <div class="btn-group" id="buttonlist"> 
                   <a class="btn btn-add " href="{{route('employees.index')}}"> 
                      <i class="fa fa-eye"></i> Back To Employee View </a>  
                   </div>
                </div>
                <div class="panel-body">
                    <div class="jumbotron bg-info text-center">
                        <h3 class=" p-3">Welcome To Employee Detail</h3>
                        <div class="container">
                            <Div class="" style="background-color: grey; border-radius: 5px; padding: 20px; margin-top: 5px; border: 2px solid red;">
                                <h2>Employee First Name : {{$employee->fistname}}</h2>
                                <h2>Employee Last Name : {{$employee->lastname}}</h2>
                                <h2>Employee Mail : {{$employee->email}}</h2>
                                <div class="form-group">
                                    <label for="">Employees  :</label>
                                    <select name="companyid" id="">
                                        @foreach ($comp as $companies)
                                            <option value="{{$companies['id']}}">{{$companies['name']}}</option>
                                        @endforeach
                                    </select>
                                 </div>
                                <h2>Company Mail : {{$employee->phone}}</h2>
                            
                                
                            </Div>
                        </div>
                        
                      
                    </div>
                </div>
                {{-- end --}}
             </div>
          </div>
       </div>
    </section>
    <!-- /.content -->
 </div>
@endsection