routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//  login route
Route::get('/', function () {
    return view('admin.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//  Admin auth
Route::match(['get', 'post'], '/Admin/Auth', 'AdminController@authentication');

Route::group(['middleware' => ['auth']], function () {

    //  middelware Authentication
    Route::match(['get', 'post'], '/company/dashboard', [CompanyController::class, 'dashboard']);

    Route::resource('companies', 'CompanyController');

    Route::resource('employees', 'EmployeeController');
});
//  Logout Middelware
Route::get('/logout', 'AdminController@logout');

resources/views/admin/addcompany/create.blade.php
@extends('admin.layouts.master')
@section('title','Add Company')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
       <div class="header-icon">
          <i class="fa fa-users"></i>
       </div>
       <div class="header-title">
          <h1>Add Company</h1>
          <small>Add Company</small>
       </div>
    </section>
    @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        
    <!-- Main content -->
    <section class="content">
     
       <div class="row">
          <!-- Form controls -->
          <div class="col-sm-12">
             <div class="panel panel-bd lobidrag">
                <div class="panel-heading">
                   <div class="btn-group" id="buttonlist"> 
                   <a class="btn btn-add " href="{{route('companies.index')}}"> 
                      <i class="fa fa-eye"></i>  View companies </a>  
                   </div>
                </div>
                <div class="panel-body">
                  <form action="{{ route('companies.store') }}" method="post" enctype="multipart/form-data">
                     @csrf
                     <div class="form-group">
                       <label for="">Company Name :</label>
                     <input type="text" name="name" id="" class="form-control" placeholder="Enter your name" value="{{old('name')}}" >
                     </div>
                     <div class="form-group">
                       <label for="">Email :</label>
                       <input type="text" name="email" id="" class="form-control" placeholder="Enter your email" value="{{old('email')}}" >
                     </div>
                    
                     <div class="form-group">
                       <label for="">Company Logo :</label>
                       <input type="file" name="image" id="" class="form-control"  >
                        
                     </div>
                     <div class="form-group">
                        <label for="">Website Url :</label>
                        <input type="text" name="web_url" id="" class="form-control" placeholder="Enter Url" value="{{old('web_url')}}" >
                      </div>
                     
         
                     <br>
                     <input type="submit" value="Submit Form" class="btn btn-info btn-lg">
         
                 </form>
                </div>
             </div>
          </div>
       </div>
    </section>
    <!-- /.content -->
 </div>
@endsection

resources/views/admin/addcompany/edit.blade.php
@extends('admin.layouts.master')
@section('title','Edit Product')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
       <div class="header-icon">
          <i class="fa fa-users"></i>
       </div>
       <div class="header-title">
          <h1>Edit Company</h1>
          <small>Edit Company</small>
       </div>
    </section>
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
@endif
        
    <!-- Main content -->
    <section class="content">
       <div class="row">
          <!-- Form controls -->
          <div class="col-sm-12">
             <div class="panel panel-bd lobidrag">
                <div class="panel-heading">
                   <div class="btn-group" id="buttonlist"> 
                      <a class="btn btn-add " href="{{url('companies')}}"> 
                      <i class="fa fa-eye"></i>  View Companies </a>  
                   </div>
                </div>
                <div class="panel-body">
                    <form action="{{ route('companies.update',$company->id) }}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                          <label for="">Company Name :</label>
                        <input type="text" name="name" id="" class="form-control" placeholder="Enter your name" value="{{$company->name}}" >
                        </div>
                        <div class="form-group">
                          <label for="">Email :</label>
                          <input type="text" name="email" id="" class="form-control" placeholder="Enter your email" value="{{$company->email}}" >
                        </div>
                        <div class="form-group">
                           <label for="">Website Url :</label>
                           <input type="text" name="web_url" id="" class="form-control" placeholder="Enter Url" value="{{$company->website}}" >
                         </div>
                        <div class="form-group">
                          <label for="">Upload  Image :</label>
                          <input type="file" name="image" id="" class="form-control"  >     
                        </div>
                       
                        <div>
                            <h5 class=" text-black">Company Logo Picture</h5>
                            <img src="{{ url('storage/app/public/company',$company->logo) }}" alt="" id="editimg" style="width: 90px; height:60px;  " class="rounded">
                          </div>
                         
                        <div class="form-group">
                          <input type="hidden" name="my_image" value="{{$company->logo}}"  >     
                        </div>
                        
          
                        <br>
                        <input type="submit" value="Submit Form" class="btn btn-info btn-lg">
                
                    </form>
                </div>
             </div>
          </div>
       </div>
    </section>
    <!-- /.content -->
 </div>
@endsection

resources/views/admin/addcompany/index.blade.php
@extends('admin.layouts.master')
@section('title','View Company')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
       <div class="header-icon">
          <i class="fa fa-product-hunt"></i>
       </div>
       <div class="header-title">
          <h1>View Companies</h1>
          <small>Companies List</small>
       </div>
    </section>
    <!-- Main content -->
    <section class="content">
       <div class="row">
          <div class="col-sm-12">
             <div class="panel panel-bd lobidrag">
                <div class="panel-heading">
                   <div class="btn-group" id="buttonexport">
                      <a href="#">
                         <h4>View Companies</h4>
                      </a>
                   </div>
                </div>
                <div class="panel-body">
                <!-- Plugin content:powerpoint,txt,pdf,png,word,xl -->
                @if (session()->has('success'))
                <div class="alert alert-success">
                    {{session()->get('success')}}
                </div>
            @endif
            @if (session()->has('error'))
                <div class="alert alert-danger">
                    {{session()->get('error')}}
                </div>
            @endif

                   <div class="btn-group">
                      <div class="buttonexport" id="buttonlist"> 
                         <a class="btn btn-add" href="{{ route('companies.create') }}"> <i class="fa fa-plus"></i> Add Company
                         </a>  
                      </div>
                   </div>
                   <!-- Plugin content:powerpoint,txt,pdf,png,word,xl -->
                   <div class="table-responsive">
                      <table id="table_id" class="table table-bordered table-striped table-hover">
                         <thead>
                            <tr class="info">
                                
                               <th>Company Name</th>
                               <th>Email</th>
                               <th>Logo</th>
                               <th>Website</th>
                               <th>Show</th>
                               <th>Edit</th>
                               <th>Delete</th>
                            </tr>
                         </thead>
                         <tbody>
                             @foreach ($comp as $item)
                             <tr>
                                <td>{{$item->name}}</td>
                                <td>{{$item->email}}</td>
                                <td> <img src="{{ url('storage/app/public/company',$item->logo)}}" alt=""  class="rounded-circle" style="width: 100px; height:100px;"></td>
                                <td>{{$item->website}}</td>
                                <td>
                                 <a href="{{ route('companies.show',$item->id) }}" class="btn btn-primary">Show</a>
                             </td>
                             
                                <td>
                                    <a href="{{ route('companies.edit',$item->id) }}" class="btn btn-success">Edit</a>
                                </td>

                                 <td>
                                    <form action="{{ route('companies.destroy',$item->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <input type="submit" value="Delete" class="btn btn-danger">
                                    </form>
                                </td>
               
                             </tr>
                             @endforeach  
                         </tbody>
                      </table>
                      <div class="d-flex justify-content-center align-items-center">
                        <div>{{$comp->links()}}</div>
                    </div>
                   </div>
                </div>
             </div>
          </div>
       </div>
       <!-- customer Modal1 -->
     
       <!-- /.modal -->
    </section>
    <!-- /.content -->
 </div> 
@endsection

resources/views/admin/addcompany/show.blade.php
@extends('admin.layouts.master')
@section('title',' Company Details')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
       <div class="header-icon">
          <i class="fa fa-users"></i>
       </div>
       <div class="header-title">
          <h1>Company Detials</h1>
          <small>Company Detials</small>
       </div>
    </section>
    @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        
    <!-- Main content -->
    <section class="content">
     
       <div class="row">
          <!-- Form controls -->
          <div class="col-sm-12">
             <div class="panel panel-bd lobidrag">
                <div class="panel-heading">
                   <div class="btn-group" id="buttonlist"> 
                   <a class="btn btn-add " href="{{route('companies.index')}}"> 
                      <i class="fa fa-eye"></i> Back To Company View </a>  
                   </div>
                </div>
                <div class="panel-body">
                    <div class="jumbotron bg-info text-center">
                        <h3 class=" p-3">Welcome To Company Detail</h3>
                        <img src="{{ url('storage/app/public/company',$company->logo) }}" alt="" id="showimg" class="rounded-circle" style="width: 100px; height:100px;">
                        <div class="container">
                            <Div class="" style="background-color: grey; border-radius: 5px; padding: 20px; margin-top: 5px; border: 2px solid red;">
                                <h2>Company Name : {{$company->name}}</h2>
                                <h2>Company Mail : {{$company->email}}</h2>
                                
                            </Div>
                        </div>
                        
                      
                    </div>
                </div>
                {{-- end --}}
             </div>
          </div>
       </div>
    </section>
    <!-- /.content -->
 </div>
@endsection